# Rename this project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_redshift_dbt_project'
version: '1.0.0'
config-version: 2

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You don't need to change these for this project.
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring seeds 
# Full documentation: https://docs.getdbt.com/docs/building-a-dbt-project/seeds
seeds:
# This declares that column names in the seed file will not be quoted when the table is created.
  +quote_columns: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this config, we tell dbt how to build the models, where to build them, which schema etc. 
# These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro. 
models:
  my_redshift_dbt_project:
    # When you rename the project up top, remember to rename it here too. 
      staging:
          # Applies to all files under models/staging 
          +materialized: view  
          # This applies a query tag named `dbt_staging` to any related queries in Redshift's Query_History
          # learn more about query tags: https://docs.getdbt.com/reference/resource-configs/Redshift-configs#query-tags
          tags: "daily"
          # You can apply tags to models, snapshots, seeds. This allows you to run based on the tag such as `dbt run --model tag:daily` which would let you run all the models tagged "daily"
          # learn more about tags: https://docs.getdbt.com/reference/resource-configs/tags#definition
      marts:
        core:
         # Applies to all files under models/marts/core
          +materialized: table
          # This defaults every model in the marts/core directory to be materialized as a table in Redshift
          query_tag: dbt_marts   
          # This applies a query tag named `dbt_marts` to any related queries in Redshift's Query_History       
